baseURL: 'https://2012monk.github.io/monk'
languageCode: en-us
title: Change of Perceptions 
theme: PaperMod

minify:
    disableXML: true
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20

params:
    env: production
    author: monk 

    displayFullLangName: true
    ShowPostNavLinks: true
    ShowToc: true
    ShowShareButtons: true
    defaultTheme: light
    # defaultTheme: dark
    # defaultTheme: auto # to switch between dark or light according to browser theme
    homeInfoParams:
        Title: "Change of Perception \n 인식의 방향"
        Content: > ##Welcome  

    socialIcons:  
        - name: github
          url: "https://github.com/2012monk"
     

outputs:
    home:
        - HTML


taxonomies:
    category: categories
    tag: tags
