baseURL: 'https://2012monk.github.io/monk'
languageCode: en-us
title: Change of Perceptions 
theme: PaperMod

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20

params:
    env: production 
    defaultTheme: light
    # defaultTheme: dark
    # defaultTheme: auto # to switch between dark or light according to browser theme
    homeInfoParams:
        Title: Change of Perception \n 인식의 방향
        Content: Welcome  

    socialIcons: github.com 
        - name: "github"
            url: "https://github.com/2012monk"
              #        - name: "<platform 2>"
              #            url: "<link2>"
     fuseOpts:
          isCaseSensitive: false
          shouldSort: true
          location: 0
          distance: 1000
          threshold: 0.4
          minMatchCharLength: 0
          keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS              

ShowToc: true
